version: '3.8'

services:
  chat:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: chat
    volumes:
      - open-webui:/app/backend/data
    env_file:
      - .env
    # environment:
    #   - 'OLLAMA_BASE_URL=http://ollama:11434'
    #   - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.translate-secure.rule=Host(`chat.davidkerr.dev`)"
      - "traefik.http.routers.chat-secure.entrypoints=websecure"
      - "traefik.http.routers.chat-secure.tls=true"
      - "traefik.http.routers.chat-secure.tls.certresolver=myresolver"
    networks:
      - web

networks:
  web:
    external: true

volumes:
  open-webui: {}
